### ISSUE TITLE
microkit tool tries to include non-LOAD segments in output.

### ISSUE THREAD

**Issue by wom-bat** [Ivan-Velickovic/sel4cp#23]
Symptom is 
```
Traceback (most recent call last):
  File "runpy", line 196, in _run_module_as_main
  File "runpy", line 86, in _run_code
  File "microkit.__main__", line 2138, in <module>
  File "microkit.__main__", line 1986, in main
  File "microkit.__main__", line 673, in build_system
  File "microkit.__main__", line 674, in <dictcomp>
  File "microkit.elf", line 304, in from_path
ValueError: negative count
```
from an ELF file that looks like:
```
$ readelf -l deadlocked.elf

Elf file type is EXEC (Executable file)
Entry point 0x200000
There are 3 program headers, starting at offset 64

Program Headers:
  Type           Offset             VirtAddr           PhysAddr              FileSiz            MemSiz              Flags  Align
  RISCV_ATTRIBUT 0x000000000000d33a 0x0000000000000000 0x0000000000000000    0x0000000000000034 0x0000000000000000  R      0x1
  LOAD           0x0000000000001000 0x0000000000200000 0x0000000000200000    0x0000000000003fa8 0x0000000000003fa8  R E    0x1000
  LOAD           0x0000000000005000 0x0000000000204000 0x0000000000204000    0x0000000000000100 0x0000000000001282  RW     0x1000

```

**Comment by wom-bat** [comment]
PR #24

**Comment by Ivan-Velickovic** [comment]
Fixed in mainline Microkit.
